"""Type stubs for the native extension module."""

import enum
import os
from typing import List, Optional

__version__: str
__api_version__: str

class Area(enum.Enum):
    Input: int
    Marker: int
    Output: int

class OperatingState(enum.Enum):
    Invalid: int
    Off: int
    Booting: int
    Stop: int
    Startup: int
    Run: int
    Freeze: int
    ShuttingDown: int
    Hold: int

def exchanges_io(state: OperatingState) -> bool: ...

class InstanceInfo:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...

class BitAddress:
    @property
    def area(self) -> Area: ...
    @property
    def byte(self) -> int: ...
    @property
    def bit(self) -> int: ...
    def __str__(self) -> str: ...

def parse_bit_address(address: str) -> BitAddress: ...

class PlcSimError(Exception):
    code: int
    code_name: str
    kind: str
    retryable: bool

class RetryableError(PlcSimError): ...
class InvalidAddressError(PlcSimError): ...
class IndexOutOfRangeError(PlcSimError): ...
class ApiNotInitializedError(PlcSimError): ...
class RuntimeManagerUnavailableError(RetryableError): ...
class InstanceNotFoundError(RetryableError): ...
class ConnectionLostError(RetryableError): ...
class TimeoutError(RetryableError): ...
class InstanceNotRunningError(RetryableError): ...

class Instance:
    def setAddressBit(self, address: str, value: bool) -> None: ...
    def getAddressBit(self, address: str) -> bool: ...
    def set_address_bit(self, address: str, value: bool) -> None: ...
    def get_address_bit(self, address: str) -> bool: ...
    def write_bit(self, area: Area, byte: int, bit: int, value: bool) -> None: ...
    def read_bit(self, area: Area, byte: int, bit: int) -> bool: ...
    def area_size(self, area: Area) -> int: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def operating_state(self) -> OperatingState: ...
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int: ...
    def is_connected(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Instance": ...
    def __exit__(self, *exc_info: object) -> bool: ...

class RuntimeManager:
    def __init__(self, api_dll_dir: Optional[os.PathLike[str] | str] = None) -> None: ...
    def is_runtime_manager_available(self) -> bool: ...
    def registered_instances(self) -> List[InstanceInfo]: ...
    def attach(self, name: str) -> Instance: ...
    def attach_by_id(self, id: int) -> Instance: ...
    def try_attach(self, name: str) -> Optional[Instance]: ...
    @property
    def version(self) -> str: ...
    def __enter__(self) -> "RuntimeManager": ...
    def __exit__(self, *exc_info: object) -> bool: ...
